# Generated by Django 5.2 on 2025-07-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_category_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_top_category',
            field=models.BooleanField(default=False, help_text='Select this to mark as a Top Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Use 1, 2, or 3 to define order for top categories. Leave as 0 if not a top category.'),
        ),
    ]
