# Generated by Django 5.2 on 2025-07-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_category_is_top_category_category_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top_product',
            field=models.BooleanField(default=False, help_text='Mark as Top Product (max 6)'),
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Use numbers 1 to 6 for top product priority. Leave 0 if not top.'),
        ),
    ]
