# Generated by Django 5.2 on 2025-07-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_product_is_top_product_product_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default/testimonial_default.jpg', upload_to='uploads/testimonials/')),
                ('remark', models.TextField()),
            ],
        ),
    ]
