# Generated by Django 5.2.8 on 2026-01-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner_image', models.ImageField(help_text='Please upload an image for the Home Page Banner in 1080*800 resolution.', upload_to='uploads/seasons/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default/category_default.jpg', help_text='Please upload an image for the category in 520*435 resolution.', upload_to='uploads/category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Please upload an image for the product in 360*250 resolution.', upload_to='uploads/products/'),
        ),
    ]
