# Generated by Django 5.2.8 on 2026-01-18 05:59

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_season_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default/category_default.jpg', help_text='Please upload an image for the category in 520*435 resolution.', upload_to=website.models.category_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Please upload an image for the product in 360*250 resolution.', upload_to=website.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=website.models.product_gallery_image_path),
        ),
        migrations.AlterField(
            model_name='season',
            name='banner_image',
            field=models.ImageField(help_text='Please upload an image for the Home Page Banner in 1080*800 resolution.', upload_to=website.models.season_image_path),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='default/testimonial_default.jpg', upload_to=website.models.testimonial_image_path),
        ),
    ]
