# Generated by Django 5.2.8 on 2026-02-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_size_alter_product_image_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
