# Generated by Django 5.2.8 on 2026-02-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_country_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='district',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.state'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.country'),
        ),
    ]
